export interface OnlineUploadedDocument {
  fileName: string;
  downloadURL: string;
}

export interface Application {
  "Application Term": string;
  "Application Id": number;
  "Application Category": string;
  "Name Arabic": string;
  "Name English": string;
  "Gender Code": string;
  "Gender Arabic": string;
  "Gender English": string;
  "Birth Date": string;
  "Marital Code": string;
  "Marital Arabic": string;
  "Marital English": string;
  "Citizenship Code": string;
  "Citizenship Arabic": string;
  "Citizenship English": string;
  "Nationality Country Code": string;
  "Nationality Country Arabic": string;
  "Nationality Country English": string;
  "Passport No": string;
  "Passport Issue Date": string;
  "Passport Place of Issue": string;
  "Passport Unified No": number;
  "Passport Expiry": string;
  "Place of Birth": string | null;
  "Country of Birth": string | null;
  "Family Book No": number;
  "Family ID": number;
  "Town ID": number;
  "Emirate ID": number;
  "Emirates ID Expiry Date": string | null;
  "Mother Emirate ID": string | null;
  "Res Area Arabic": string;
  "Res Area English": string;
  "Res Emirate Code": string | null;
  "Res Emirate Arabic": string | null;
  "Res Emirate English": string | null;
  "Mobile": string;
  "Mobile2": string;
  "Email": string;
  "Alternative Email": string | null;
  "Legal Gaurdian Name": string;
  "Gaurdian Phone": string;
  "Gaurdian Email": string;
  "School Zone Code": string;
  "School Zone": string;
  "School Name Code": string;
  "School Name Arabic": string;
  "School Name English": string;
  "Study Type Code": string;
  "Study Type": string;
  "Study Program Code": string;
  "Study Program": string;
  "Student ID (MOE/ADEK/KHDA/SPEA)": string;
  "Is POD Student": string | null;
  "POD - Program Type": string | null;
  "POD - Exception Category": string | null;
  "POD - Exception Services": string | null;
  "Institution Code": string;
  "Institution Name English": string;
  "Institution Name Arabic": string;
  "Institution Campus Code": string;
  "Institution Campus English": string;
  "Institution Campus Arabic": string;
  "Institution Major Code - 1": string | null;
  "Institution Major English - 1": string | null;
  "Institution Major Arabic - 1": string | null;
  "Institution Program Code - 1": string | null;
  "Institution Program English - 1": string | null;
  "Institution Program Arabic - 1": string | null;
  "Institution Major Code - 2": string | null;
  "Institution Major English - 2": string | null;
  "Institution Major Arabic - 2": string | null;
  "Institution Program Code - 2": string | null;
  "Institution Program English - 2": string | null;
  "Institution Program Arabic - 2": string | null;
  "Institution Major Code - 3": string | null;
  "Institution Major English - 3": string | null;
  "Institution Major Arabic - 3": string | null;
  "Institution Program Code - 3": string | null;
  "Institution Program English - 3": string | null;
  "Institution Program Arabic - 3": string | null;
  "Institution Housing": string | null;
  "Institution Transportation": string | null;
  "High School Average": string | null;
  "High School Arabic": string | null;
  "High School English": string | null;
  "High School Maths": string | null;
  "High School Physics": string | null;
  "High School Chemistry": string | null;
  "High School Biology": string | null;
  "High School Term2 Average": string | null;
  "High School Term2 Arabic": string | null;
  "High School Term2 English": string | null;
  "High School Term2 Maths": string | null;
  "High School Term2 Physics": string | null;
  "High School Term2 Chemistry": string | null;
  "High School Term2 Biology": string | null;
  "High School Term1 Average": string | null;
  "High School Term1 Arabic": string | null;
  "High School Term1 English": string | null;
  "High School Term1 Maths": string | null;
  "High School Term1 Physics": string | null;
  "High School Term1 Chemistry": string | null;
  "High School Term1 Biology": string | null;
  "High School G11 Average": string | null;
  "High School G11 Arabic": string | null;
  "High School G11 English": string | null;
  "High School G11 Maths": string | null;
  "High School G11 Physics": string | null;
  "High School G11 Chemistry": string | null;
  "High School G11 Biology": string | null;
  "High School G10 Average": string | null;
  "High School G10 Arabic": string | null;
  "High School G10 English": string | null;
  "High School G10 Maths": string | null;
  "High School G10 Physics": string | null;
  "High School G10 Chemistry": string | null;
  "High School G10 Biology": string | null;
  "IELTS Overall Band": string | null;
  "TOEFL iBT - Total": string | null;
  "TOEFL ITP - Total": string | null;
  "TOEFL Paper Based": string | null;
  "SAT Physics": string | null;
  "SAT Chemistry": string | null;
  "SAT Biology": string | null;
  "SAT 1 Maths": string | null;
  "SAT 2 Maths": string | null;
  "ITIMAD Reference Number": number | null;
  "ITIMAD Status": string | null;
  "ITIMAD Status Date": string | null;
  "Approval Institution Name English": string | null;
  "Approval Institution Name Arabic": string | null;
  "Approval Institution Campus English": string | null;
  "Approval Institution Campus Arabic": string | null;
  "Approval Institution Major English": string | null;
  "Approval Institution Major Arabic": string | null;
  "Approval Institution Program English": string | null;
  "Approval Institution Program Arabic": string | null;
  "Approval Status": string | null;
  "Conditional Approval Status Remarks": string | null;
  "Approval Status Remarks": string | null;
  "Student Acceptance Status": string | null;
  "University Offer Letter": string;
  "RecordID": string;
  "ReferenceCode": string;
  "Application Status": string;
  "Created Date": string;
  "Updated Date": string;
  "OnlineUploadedDocuments": OnlineUploadedDocument[];
  "DocumentsZip": string;
}

export type ApplicationsResponse = Application[]; 